package pl.fester3k.androcode.datatypes;

public enum Feature {
	RIDE,
	TELEPHONY_CONNECTION, INTERNET_CONNECTION, WIFI_CONNECTION, BLUETOOTH_CONNECTION, DATA_TRANSFER_CONNECTION, TETHERING, 
	CAMERA, FLASHLIGHT, AUDIO_OUT, AUDIO_IN,
	LOCATION, LOCATION_GPS, LIGHT_SENSOR, GRAVITY_SENSOR, HUMIDITY_SENSOR, LINEAR_ACCELERATION_SENSOR, GYROSCOPE_SENSOR, TEMPERATURE_SENSOR, PROXIMITY_SENSOR, ACCELEROMETER_SENSOR, MAGNETIC_FIELD_SENSOR, AUDIO_SENSOR, PRESSURE_SENSOR, RECORD_VIDEO;  
}
