package pl.fester3k.androcode.datatypes;

//TODO Zabezpieczyc sie przed bledami w pisowni feature
public enum Feature {
	RIDE,
	
	SMS, //DONE
	EMAIL, //DONE
	WIFI_CONNECT, 
	CAMERA,  //DONE 
	RECORD_VIDEO, //DONE
	FLASHLIGHT, //DONE
	AUDIO_OUT,  
	RECORD_AUDIO, 	//DONE
	TTS, 		//DONE 1/4
	
	LOCATION, 		//DONE
	COMPASS,
	LIGHT_SENSOR,   //DONE
	GRAVITY_SENSOR, //DONE 
	HUMIDITY_SENSOR,//DONE  
	LINEAR_ACCELERATION_SENSOR, //DONE 
	GYROSCOPE_SENSOR,  //DONE
	TEMPERATURE_SENSOR,  //DONE
	PROXIMITY_SENSOR, //DONE
	ACCELEROMETER_SENSOR, //DONE
	MAGNETIC_FIELD_SENSOR, //DONE
	AUDIO_SENSOR, 	//DONE
	PRESSURE_SENSOR;//DONE  
}
