package pl.fester3k.androcode.datatypes;

//TODO Zabezpieczyc sie przed bledami w pisowni feature
public enum Feature {
	RIDE,
	
	SMS_SENDER, 
	EMAIL_SENDER, 
	WIFI_CONNECTION, 
	TETHERING, 
	CAMERA,  //DONE 
	RECORD_VIDEO, //DONE
	FLASHLIGHT, //DONE
	AUDIO_OUT, 
	AUDIO_IN,//DONE
	
	LOCATION, 
	LOCATION_GPS, 
	COMPASS,
	LIGHT_SENSOR,   //DONE
	GRAVITY_SENSOR, //DONE 
	HUMIDITY_SENSOR,//DONE  
	LINEAR_ACCELERATION_SENSOR, //DONE 
	GYROSCOPE_SENSOR,  //DONE
	TEMPERATURE_SENSOR,  //DONE
	PROXIMITY_SENSOR, //DONE
	ACCELEROMETER_SENSOR, //DONE
	MAGNETIC_FIELD_SENSOR, //DONE
	AUDIO_SENSOR, 
	PRESSURE_SENSOR;//DONE  
}
